# @format

name: GitHub Deploy Workflow

permissions: write-all

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '18.x'
      - name: install spider pkg and run
        run: |
          cd spider && npm install
          npm run start
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build pages
        run: |
          cd web && npm install && npm run build
          mv out ../build
          cp data.json ../build/
      - name: Update release
        run: |
          gh release upload --clobber v0.1 build/data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}