# @format

name: Github Sync Repositories

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Mirroring
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing Run
        run: python sync.py
        env:
          GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
