# @format

name: Github Sync Repositories

permissions: write-all

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing Run
        run: gh repo sync kern-crates/ByteOS -b main
        env:
          GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
